### ISSUE TITLE
Powermatcher website needed

### ISSUE THREAD

**Issue by alex254** [flexiblepower/FAN-wiki#1]
A website is needed to attract new users and developers.
- [x] Mission statement
- [x] Mention licence
- [x] List of software functions
- [x] development status
- [x] Coding guidelines (where to find)
- [x] Communication channels
- [x] Issues (Where to find)
- [x] To do list
- [x] How to install
- [x] Introduction video
- [x] How projects relate to each other
- [x] Add PowerMatcher youtube video (TNO)
- [x] PowerMatcher Trademark rules
- [x] Why joining the development?

To do
- [x] remove all non website stuff from the gh-pages branch
- [x] Copy more content from current PowerMatcher website
- [x] Remove demo posts

**Comment by Sander3003** [comment]
Example: https://developer.rackspace.com/blog/walk-n-doc/

**Comment by Sander3003** [comment]
First text added to:
http://flexiblepower.github.io/powermatcher/

**Comment by Sander3003** [comment]
@victor481 will help with this as well

**Comment by Sander3003** [comment]
Make sure to set UTF-8 in eclipse.

https://help.github.com/articles/page-build-failed-file-is-not-properly-utf-8-encoded

**Comment by Sander3003** [comment]
The website will be moved to flexiblepower.github.io.

Website setup:
![image](https://cloud.githubusercontent.com/assets/7427358/4230357/ad21d032-3982-11e4-8028-d04f920c0db7.png)

The first content draft will be ready 24 September.

**Comment by Sander3003** [comment]
Website moved to flexiblepower.github.io and redirected trafic from flexiblepower.github.io/powermatcher to flexiblepower.github.io. More menu's pages added to the website bar. @alex254 @victor481

**Comment by Sander3003** [comment]
Where to we want to place: "How projects relate to each other" (what is in the github repositories)?

**Comment by Sander3003** [comment]
@alex254 will add his content
@victor481 will merge the buisiness cases information
Send out current content for review 9 oct.

**Comment by Sander3003** [comment]
@victor481 can you upload your latest changes to send the review?
