### ISSUE TITLE
Demo environment needed

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#10]
Users should have a low barrier to test the FPAI/PowerMatcher software, a demo evironment can help with this.

**Comment by wilcowijbrandi** [comment]
I have create a zip containing a preconfigured FPAI with a small PowerMatcher cluster and some simulated devices. It also contains a nice manual that explains how to get it running and what it does. What would be the best place to put it? On the github pages?

**Comment by alex254** [comment]
yea create a new respository and call it somethig like "Start Here!"

**Comment by wilcowijbrandi** [comment]
I don't think that's a good idea. This demo is just to see something move quickly. For new developers we're already working on the fpai-examples repository.

**Comment by marcdejonge** [comment]
What about the releases of the fpai-demo repository? We can store the zip
there and reference to it from the Wiki.

**Comment by Sander3003** [comment]
Github (pages) might be the best way (if this works).
