### ISSUE TITLE
PowerMatcher promotion - Business users

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#17]
Current approach idea's:
*Connect with potential users/partners and make appointments to meet with them on the EUW 
*Promote on Linkedin (All FAN members and related individuals)
*Promote within your own network (All FAN members and related individuals)
*Website powermatcher.org needs to be ready!
*2 week before the EUW start:send out an press message
*Fist 2 days @ the EUW: meet potential users and give out a flyer to remind them; They can come to the presentation on Thursday as well. Very intreseted people can be invited to the Q&A workshop.
*Thursday 9:00 presentation (20 minutes) (@alex254) (will mention the Hacketon)
*VIOS presentation (Technolution)
*PowerMatcher & Consumer Behaviour presentation (Stedin)
*Thursday 11:00 PowerMatcher Workshop  (45 minutes) Q&A session
*Show DEMO on the energy experience booth
*Interview Bert den Ouden by Engerati

Notes:
*Flyers are not allowed on the energy experience in any form (e.g. flyering). The energy experience is non-commercial 
*Contact pulic affairs form Alliander and TNO in case of interviews or media contact
*Bert need to contact Engarati himself to discuss the subjects

To do:
- [x] Aks for flyer option in EUW bag @sander3003 Result: This is not an option (only for sponsors)
- [x] Design flyer
- [x] Print flyer
- [x] Look for potiential PM/FPAI users and meet them at the EUW
- [x] Promote EUW/FAN within your own (private/company) network
- [x] Design presentation and workshop
- [x] Give the presentation and workshop
- [x] Invite people to the workshop
- [x] Connect with press (Done by @Sander3003)
- [x] Write press message 
- [x] Send out press message (send it to the EUW organisation & E-mail Energy experiance, media gets notified by the EUW organisation, media itself can decide to publish a press release)
- [x] Arrange interview Bert

Other:
- [x] Add project to Ohloh.net / Adding the projects to https://code.ohloh.net/ can help to promote the project.
- [x] 2nd International  Transactive Energy Conference (December USA, submit papers by 5th of September)
- [x] Demo made by @marcdejonge 
- [x] Fix website #1 

-[ ] See new users on github ;)

**Comment by Sander3003** [comment]
@alex254 will help me out with this

**Comment by marcdejonge** [comment]
We're also busy on creating a new release. Hopefully this will be done by October. One part of this release is a demonstration that can be downloaded and run by anyone. Maybe something to add to the list?

**Comment by Sander3003** [comment]
Done

**Comment by Sander3003** [comment]
This are the options to get the news out on the EUW:
- EUW press database
- event website
- EUW Newsletter and targeted emailshots
- Engerati

http://portal.european-utility-week.com/shareyournews

**Comment by alex254** [comment]
And the EUW goody bag?

Van: Sander Jansen [mailto:notifications@github.com]
Verzonden: woensdag 3 september 2014 13:24
Aan: flexiblepower/FAN-wiki
CC: Krstulovic, Alexander
Onderwerp: Re: [FAN-wiki] PowerMatcher promotion - Business users (#17)

This are the options to get the news out on the EUW:
-   EUW press database
-   event website
-   EUW Newsletter and targeted emailshots
-   Engerati

http://portal.european-utility-week.com/shareyournews

**Comment by Sander3003** [comment]
I send an e-mail to the EUW organisation and asked for the possibilities. 
Answer: Only sponsors can put stuff in the conference bag.

**Comment by Sander3003** [comment]
New versions:
![pmside](https://cloud.githubusercontent.com/assets/7427358/4592526/b65d7b4a-507c-11e4-88dc-21f0b120b106.png)
![fanside](https://cloud.githubusercontent.com/assets/7427358/4592527/b67b1510-507c-11e4-975c-6516a2de4735.png)

**Comment by wilcowijbrandi** [comment]
Cool! Ik zou alleen even concequent zijn met hoe je de namen van de presentators schrijft (met of zonder achternaam). De URL onderaan moet natuurlijk http://www.flexiblepower.org zijn (de '//' is weggevallen). Is het overigens handig om de Q&A sessie er ook op te zetten?

**Comment by Sander3003** [comment]
What did Claudia say about the Q&A workshop/session?

**Comment by Sander3003** [comment]
Thanks for the feedback, here is a new version:
![pmside](https://cloud.githubusercontent.com/assets/7427358/4612916/279e3746-52cf-11e4-8c1b-b58a4b6e6e2c.png)
![fanside](https://cloud.githubusercontent.com/assets/7427358/4612917/2af13272-52cf-11e4-8376-72431061acbe.png)
More feedback is appreciated!

**Comment by Sander3003** [comment]
@wilcowijbrandi Do you have a vectorfile of the "Flexibepower Alliander Network THE POWERMATCHER FOUNDATION" logo (used on flexiblepower.org)?

**Comment by Sander3003** [comment]
Repositories added to openhub.net
https://www.openhub.net/p/powermatcher

https://www.openhub.net/p/fpai-core

**Comment by Sander3003** [comment]
A widget could be added to the website.

https://www.openhub.net/p/powermatcher/widgets

**Comment by Sander3003** [comment]
Done
