### ISSUE TITLE
Check the current demo and manual on errors/isssues

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#20]
Please report your findings here!

**Comment by wilcowijbrandi** [comment]
It's online at http://flexiblepower.github.io/downloads/PowerMatcherSuite_13.10_Demo.zip

**Comment by Sander3003** [comment]
https://github.com/flexiblepower/flexiblepower.github.io/blob/master/downloads/PowerMatcherSuite_13.10_Demo.zip?raw=true Works better

**Comment by Sander3003** [comment]
Demo works fine for me. Feature request: Display a message in the terminal that the demo started. With the suggestion that you can open a browser to go to localhost:8080.

**Comment by Sander3003** [comment]
Is this done?

**Comment by Sander3003** [comment]
Add improvments in the new release.

**Comment by Sander3003** [comment]
Fixed so far with new release
