### ISSUE TITLE
Improve documentation setup (gitbook instead of github wiki)

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#22]
A nightly build (in PDF) of the current wiki's would be nice.

**Comment by Sander3003** [comment]
Will be done by gitbooks. FPAI wil start first.

@alex254 can help with PowerMatcher

**Comment by Sander3003** [comment]
Example: http://gitbookio.gitbooks.io/javascript/

**Comment by Sander3003** [comment]
Inspiration for the new setup: https://www.youtube.com/watch?v=kP3R6WBbbTY
A "fix this page" button would be nice for newbees to easily add documentation improvements.

Disable github wiki's where needed (see settings)

**Comment by wilcowijbrandi** [comment]
Nice talk! We should maybe also add a chapter in the documentation about the documentation itself, and on how to improve it.
Anyway, I have put everything in Jenkins for the fpai-documentation. Builds (html and pdf) end up here, sorted by branch: http://fpai-ci.sensorlab.tno.nl/builds/fpai-documentation/
I think that the jenkins server is fine for intermediate versions. When we have a final release of the documentation (e.g. FPAI 14.10, PowerMatcher 2.0) we can copy them manually to the flexiblepower.github.io site.

**Comment by Sander3003** [comment]
Can you add a ""fix this page" button to the html version?
An epub file would be nice as well.

**Comment by wilcowijbrandi** [comment]
Found a plugin! :)
http://plugins.gitbook.com/plugin/edit-link

I'll look into it!

**Comment by Sander3003** [comment]
Nice! This makes it easy to edit for everyone!
