### ISSUE TITLE
Device drivers list needed for website

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#24]
What device drivers are currently available?

**Comment by Sander3003** [comment]
@wilcowijbrandi @alex254 will make a list of current drivers: end of next week

**Comment by marcdejonge** [comment]
See https://github.com/flexiblepower/fpai-devices/blob/development/README.md

**Comment by wilcowijbrandi** [comment]
The S0 driver should also be added to that list (and repository)

**Comment by Sander3003** [comment]
Added to: http://flexiblepower.github.io/in-practice/

**Comment by Sander3003** [comment]
@konsmanmj can you help us out with this? Please add them to: http://flexiblepower.github.io/in-practice/driver-list/

**Comment by alex254** [comment]
Tip from somebody; to extend this Driver list with pictures of the actual devices and links to the manufacturers!

**Comment by Sander3003** [comment]
Hi guys, I fixed the broken links on the PowerMatcher website (Thanks to @Bob-Ran / @wilcowijbrandi ) for the tips. I updated the FPAI driver table (with FPAI-apps as resource). Links to actual devices are still missing.

**Comment by Sander3003** [comment]
Fixed!
