### ISSUE TITLE
FOSDEM: Call for participation: main tracks and developer rooms

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#26]
@marcdejonge will send @sander3003 some examples
Needs to be done before 1 of October.

**Comment by Sander3003** [comment]
@marcdejonge the deadline is tomorrow

**Comment by marcdejonge** [comment]
I sent you the abstracts...

**Comment by Sander3003** [comment]
Done, Thanks for your input!

**Comment by Sander3003** [comment]
My lightning talk proposal is rejected. I will take a look whats going on.
