### ISSUE TITLE
http://fpai-ci.sensorlab.tno.nl:8080/ is not accessible

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#29]
Can somebody fix this?

**Comment by wilcowijbrandi** [comment]
Port 80 works fine from the Internet, port 8080 only from the TNO network. Probably something with the firewall. @marcdejonge ?

**Comment by Sander3003** [comment]
Interesting option: https://developer.github.com/guides/building-a-ci-server/

**Comment by Sander3003** [comment]
@jvdgeest can you help @marcdejonge with this?

**Comment by marcdejonge** [comment]
Fixed it. Now jenkins serves the main page, but you can easily click through the builds :)

http://fpai-ci.sensorlab.tno.nl/

**Comment by Sander3003** [comment]
Nice, good work!
