### ISSUE TITLE
Review core/ non-core text

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#30]
https://github.com/flexiblepower/FAN-wiki/wiki/Governance

Can you take a look at this?

I will ask @LoekJa as well.

**Comment by wilcowijbrandi** [comment]
I was thinking of making the separation something like this:

**Core**
Major changes, such as
- Changes in the PowerMatcher protocol
- Changes in behaviour of PowerMatcher agents
- Changes in PowerMatcher cluster configuration
- Changes in the FPAI Energy Flexibility Interface (EFI)
- Changes in FPAI Application specifications
- Changes in FPAI remote management protocol

**Non-core**
Minor changes, such as
- Bug fixes
- New or changed FPAI Apps
- PowerMatcher agents for specific appliances or objectives

**Comment by Sander3003** [comment]
Thanks for your input. I will discuss it with Loek as well.
