### ISSUE TITLE
Review http://flexiblepower.github.io/ content

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#33]
Please report your findings here or send in a pull request!

**Comment by Sander3003** [comment]
Richards input: add more FPAI to the website, Maybe we could add a Why FPAI page?

**Comment by wilcowijbrandi** [comment]
I think it's very important that we make clear what the PowerMatcher, the FPAI and the PowerMatcherSuite exactly is. Maybe we should make an infographic which gives an overview and put it on the homepage.

Also, I agree with Richard. PowerMatcher and FPAI are both seperate technologies, which don't depend on each other. But together they are of course a very strong combination. ;) They both deserve attention on this website.

I think we should restructure the menu. I think the main topics are:
- What is the FAN, what is the PowerMatcher, what is the FPAI and what is the PowerMatcherSuite?
- PowerMatcher
- FPAI
- The open source community and how can I help

**Comment by wilcowijbrandi** [comment]
My proposal for the menu structure:
- **Home** PowerMatcher vs. FPAI infographic
- **News**
- **PowerMatcher**
  - **Why PowerMatcher**
  - **Business case** (now: PowerMatcher Businesscases)
  - **Features**
  - **PowerMatcher explained** (now: Technology)
- **FPAI**
  - **Why FPAI** (new)
  - **The FPAI platform** (new)
  - **Connected devices** (now: Existing practices)
- **In practice**
  - **Try it now!** (now: How to get started)
  - **In operation**  
- **Get involved**
  - **Open Source** (now: Why Open Source)
  - **Why Joint?**
  - **Contribute**
- **About**

**Comment by alex254** [comment]
- Discussion on the correct menu structure was inconclusive; left for next time with bigger group
- @wilcowijbrandi makes infograph with powermatcher & fpai for homepage
- More content FPAI or less content PowerMatcher

**Comment by Sander3003** [comment]
Add fork me on github button or other github link.

**Comment by Sander3003** [comment]
[plaatje] is missing on http://flexiblepower.github.io/technology/powermatcher/

**Comment by Sander3003** [comment]
Thanks @alex254 !
