### ISSUE TITLE
I quit as community manager for the PowerMatcherSuite

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#56]
Hi Guys,

Together with my manager I deiced to quit my part-time role as the PowerMatcherSuite community manager. I will stop after the EUW this year. I can't combine it any longer with my other activities.

Gr Sander

**Comment by wilcowijbrandi** [comment]
Hi Sander,

It is a pity to hear you are not able to participate in the community council anymore. Thanks for all your help. You did a great job bootstrapping the FAN development community!

Cheers,
Wilco
