### ISSUE TITLE
Question:My Question

### ISSUE THREAD

**Issue by Roebu** [flexiblepower/FAN-wiki#64]
I am trying to get started with PowerMatcher and have been trying out the fpai-apps-runtime-release-15-05 demo. It starts up, prints out lots of debug and info message and I can log into the FlexiblePower demo screen. Beyond that, however, it does not appear to do anything interesting. I can see various devices (storage, smartpv, dishwasher, uncontrolled simulation, powermatcher) but they don't appear to do anything. What am I doing wrong?  

Thanks, - Rob

Btw, I see lots of messages like this in the log.

12:37:09.491 WARN  o.f.u.s.UncontrolledSimulation       - Trying to publish a new state without a manager connected (org.flexiblepower.uncontrolled.simulation.PowerStateImpl@94209d0)

**Comment by alex254** [comment]
Hi Rob,

When you start up on of the scenario’s, you can click on for instance the cloud in the PV simulationwidget to change it to the sun. You will see that the PV will start to produce more and hence the price in the powermatcher will go down and the dishwasher will turn on. If you like a more in depth walkthrough we can schedule a call and I can walk you through the basics, it will save you time. Are you planning to work with the source code?

Kind regards,

Alex

Van: Rob Ward [mailto:notifications@github.com]
Verzonden: donderdag 3 december 2015 12:47
Aan: flexiblepower/FAN-wiki
Onderwerp: [FAN-wiki] Question:My Question (#64)

I am trying to get started with PowerMatcher and have been trying out the fpai-apps-runtime-release-15-05 demo. It starts up, prints out lots of debug and info message and I can log into the FlexiblePower demo screen. Beyond that, however, it does appear to do anything interesting. I can see various devices (storage, smartpv, dishwasher, uncontrolled simulation, powermatcher) but they don't appear to do anything. What am I doing wrong?

Thanks, - Rob

Btw, I see lots of messages like this in the log.

12:37:09.491 WARN o.f.u.s.UncontrolledSimulation - Trying to publish a new state without a manager connected (org.flexiblepower.uncontrolled.simulation.PowerStateImpl@94209d0https://github.com/org.flexiblepower.uncontrolled.simulation.PowerStateImpl/FAN-wiki/commit/94209d0)

**Comment by alex254** [comment]
Ah actually the managers might not be connected to the drivers... can you click on the 'dashboard button'..it will open up the 'connections' page..some elements might have lossed their connection: please connect as follows:

pv simulation -> uncontrollable manager -> powermatcher
dishwasher -> timeshifter manager - > powermatcher
storage -> buffer manager -> powermatcher
uncontrolled simulation -> uncontrollable -> powermatcher
.

**Comment by Roebu** [comment]
Alex,

Thanks for the quick response.

> When you start up on of the scenario’s, you can click on for instance the cloud in the PV simulationwidget to change it to the sun. 

I tried that but, as soon as I click on the sun, it reacts briefly (I see the power output go up to 2000W or so) but then almost immediately goes back to 0W again.

**Comment by alex254** [comment]
see my last reply

**Comment by Roebu** [comment]
I see the following:
pv simulation -> uncontrollable manager -> powermatcher controller
battery simulation -> battery manager -> -> powermatcher controller

The connections seem to be the same regardless of which demonstration I choose in the demo scenario box.

**Comment by Roebu** [comment]
> If you like a more in depth walkthrough we can schedule a call and I can walk you through the basics, it will save you time

This might be an idea.

> Are you planning to work with the source code?

Quite possibly. I'd first like to get a better understanding of what exactly PowerMatcher can do.

**Comment by alex254** [comment]
sure lets schedule a call, could you email me on alexander.krstulovic@alliander.com?  I am in the us until next week wednesday, so preferably after that.
