### ISSUE TITLE
Building PowerMatcher

### ISSUE THREAD

**Issue by Roebu** [flexiblepower/FAN-wiki#70]
Is it possible to build PowerMatcher without using Eclipse? I want to set up a "headless" build, i.e. one that can run unattended.

**Comment by wilcowijbrandi** [comment]
Yes, that is certainly possible! You can use Gradle for building (and testing). When checking out the git repository don't forget to also checkout the git submodule (use `git submodule init` and `git submodel update`). Please note that the Gradle scripts do not work with every version of Gradle. I use Gradle 2.5 and this works fine.

`gradle tasks` gives you an overview of all possible build tasks.

`gradle distribute` generates a complete distributed of the code, including a 'runtime zip archive'. When you extract this archive you can start PowerMatcher from a commandline. It contains a `run.bat` file for Windows and a `run.sh` file for Linux.
